# Generated by Django 4.2.7 on 2023-11-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UnisApp', '0002_remove_profile_profile_pic_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='img/logo-profile.jpg', upload_to=''),
        ),
    ]
